name: CI

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Check application
        run: |
          test -f bun.lock
          bun install --frozen-lockfile
          bun run lint
          bun run test
          bun run build
